services:
  db:
    image: postgres:17-alpine
    container_name: samba_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - config/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data:rw

  # INTERNAL SERVICE
  core:
    build:
      context: cmd
      dockerfile: Dockerfile
    container_name: samba_core
    env_file:
      - config/.env
    depends_on:
      - db

  gateway:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: samba_gateway
    env_file:
      - config/.env
    depends_on:
      - core
    ports:
      - 8080:8080

volumes:
  pg_data:
